### ISSUE TITLE
fdopen spec doesn't fail on LuaJIT

### ISSUE THREAD

**Issue by rrthomas** [luaposix/luaposix#218] opened 2015-03-03 15:01 UTC
See #217, which I can confirm by running the spec code manually, and yet the test doesn't fail. Specifically, this line:

            expect (f:write ("writing to fdopen(stdout)\n")).not_to_be (nil)

must raise an error in LuaJIT, yet that error doesn't get propagated, and the test passes in Travis.

**Comment by rrthomas** [comment] 2015-03-03 15:01
(I will shortly remove fdopen support for LuaJIT, but I think this issue should still be pursued.)

**Comment by gvvaughan** [comment] 2015-03-03 23:20
The problem is that f:write() is not happening inside the special capture environment that Specl sets up with io.stdout, io.write etc overridden with new functions that save whatever is output into strings... hence the output to *actual* stdout in the travis logs.

I haven't given much thought to a better way to redirect in process example streams for capture automatically, though you can use `specl.shell` to run the `expect` expression in a subshell, like some of the other specs where the process streams are connected up for capture.  I didn't do this by default because its an order of magnitude slower than manually forking for the few examples that need it.  I'll fix this up for you in a few days if you don't get around to it first.

Unfortunately, even my rewrite of the Specl core doesn't have a better solution.  If you have one, I'd be glad to implement it!

**Comment by rrthomas** [comment] 2015-03-04 12:43
The thing I really don't understand (and forgive me if I missed something in your reply) is not so much why the output isn't caught as why the error isn't caught: the point is, LuaJIT actually raises an error. Surely any unexpected error should be detected?

**Comment by gvvaughan** [comment] 2015-03-04 13:20
All that Specl does is change each call to `expect (foo)` to actually run `expect (pcall (function () return foo))`; if the first result of the pcall i.e. the first argument to the expect function, is falsey then an error *can* be detected by the `to_raise` matched.  I think you are likely correct that an error raised when passing the expect result to any other matcher should take precedence over the specified matcher all the time.

Some of the matchers in `specl.shell` and `specl.inprocess` already code around this if the child process returns abnormally, so it should just be a matter of generalizing that code and promoting it to the Matcher base class where everything will inherit a copy.  I'll add this to the pending issues Inneed to fix before pushing the rewritten Specl core.

Cheers!

**Comment by gvvaughan** [comment] 2016-02-26 01:10
Fixed by 4223c9ad07252bdaf52db57d93cf8ccb708907b1

**Closed by gvvaughan** 2016-02-26 01:10 UTC
