### ISSUE TITLE
Problem with installation of C libs

### ISSUE THREAD

**Issue by rrthomas** [luaposix/luaposix#190] opened 2014-12-16 01:18 UTC
I just ran `luarocks install luasec` and it worked fine, so I think my luarocks 2.2.0 setup is OK. When I run `luarocks make` in current luaposix git, it installs the C libraries in the wrong place: under `lib_dir/lua/5.2` rather than under `lib_dir`. Then Lua can't find them.

Obviously, it is luarocks that finally moves the libraries to the wrong place, not luaposix's build system itself.

My `lib_dir` as set in my LuaRocks config is:

        lib_dir = home.."/.local/lib/"..arch.."/lua/"..lua_version,

In the auto-generated `build-aux/luarocks-config.lua`, I have:

    variables = {
      LUA = "/home/rrt/.local/bin/x86_64-linux-gnu/lua",
      LUA_BINDIR = "/home/rrt/.local/bin/x86_64-linux-gnu",
      LUA_INCDIR = "",
      LUA_LIBDIR = "",
    }

Is that wrong? (Obviously the default computed values for `LUA_LIBDIR` and `LUA_INCDIR` won't work with my setup.)

This is going back to the conversation we had around January 15th 2014. Unfortunately I can't find a fix other than manually moving the libs to the right location after installation.

Setting `LIBDIR` in the call to luarocks doesn't help. (Setting `LUA_LIBDIR` is plain ignored.)

As far as I can see this is because in `local.mk` it is `luaexecdir`, which defaults in `ax_lua.m4` to `$exec_prefix/lib/lua/$LUA_VERSION`, which is wrong. I can't see how to set it when calling `luarocks`, since that doesn't give me access to the command line sent to `make`.

**Comment by gvvaughan** [comment] 2015-01-19 23:11
Yuck

I'm not inclined to investigate this anymore myself, because I have a new Luke prototype working for Lua only builds, and plan to move to using Luke instead of autoconfuse for build related tasks (obsoleting slingshot along the way).  So rather than spending time on this and a bunch of other niggly little corner cases with configured builds, I'd rather work on supporting C module builds with Luke...

Of course, I'd be very happy if you find a solution, and will gratefully apply any patches that you need in that case :-)

**Comment by daurnimator** [comment] 2015-02-16 22:24
These luarocks settings can be found in the rather hidden away file `luarocks/site_config.lua`
I think this issue is related to how you `./configure`'d your luarocks installation.

**Comment by hishamhm** [comment] 2015-02-26 05:43
Hi, `$(LIBDIR)` as written in the rockspec file is meant to be the final destination of all binary modules. Note that this is a temporary directory in a sandbox location, and not the final destination where the modules will live (ie, if LuaRocks is configured to install in `/usr/local/lib/lua/5.2`, this is where they'll end up in, but this is _not_ the value of `$(LIBDIR)`. This is deliberate, to ensure relocatable builds and avoid hardcoded paths.)

I see that the rockspec is already passing `$(LIBDIR)` to the `configure` script as `--libdir='$(LIBDIR)'`, so things are supposed to work. Apparently someone is adding `/lua/5.2` after the fact, but it's not LuaRocks.

**Comment by rrthomas** [comment] 2015-02-26 08:59
@daurnimator It's nothing to do with my LuaRocks config: see the initial report, where I was able to install luasec with no problem to the expected location. In any case, the contents of my `luarocks/site_config.lua` is fine.

**Comment by hishamhm** [comment] 2015-02-26 14:36
Hi all,

I installed luaposix here to see if I could reproduce the issue and sure enough, posix.so is not being deployed here either.

The bad news is that you've just hit a serious design limitation in LuaRocks that no one had never bumped into in the last eight years:

You guys have a .lua and a .so module with the same name.

The manifest format stores module references in a ["foo.bar"] = "path/to/foo/bar.lua" model. With posix.so and posix.lua, the key gets overwritten.

I am deeply sorry about this, but I honestly don't see how this can be fixed in the LuaRocks end without some serious reengineering and compatibility breakage.

If posix.so is used only internally by the .lua modules and you're willing to accept renaming it to posix/core.so, I volunteer to submit a patch.

**Comment by rrthomas** [comment] 2015-02-26 15:11
@hishamhm , thanks very much for the test and offer of a patch. I wonder if however you have found a different bug? The install is now working fine for me, whereas what you report is that it won't be correctly recorded in the manifest, and so the files won't be managed correctly later (e.g. when installing multiple versions of the rock). I don't understand why `posix.so` isn't being correctly installed for you…

**Comment by rrthomas** [comment] 2015-02-26 15:14
(I spent some time trying to work out when the problem was fixed for me, since I no longer have to set `luaexecdir` at configure time, and it has the wrong-for-me default value; it seems that the setting in the `install_command` is now being respected, for whatever reason. It could be that this was fixed in slingshot rather than luaposix.)

**Comment by daurnimator** [comment] 2015-02-26 16:17
> The bad news is that you've just hit a serious design limitation in LuaRocks that no one had never bumped into in the last eight years:
> 
> You guys have a .lua and a .so module with the same name.
> 
> The manifest format stores module references in a ["foo.bar"] = "path/to/foo/bar.lua" model. With posix.so and posix.lua, the key gets overwritten.
> 
> I am deeply sorry about this, but I honestly don't see how this can be fixed in the LuaRocks end without some serious reengineering and compatibility breakage.

I actually have run into this before, I didn't realise it was an unreported issue.

My workaround was to use a key like ["posix.init"] for the lua module.
Due to "*/?/init.lua" being in the lua path it works out fine :)

**Comment by gvvaughan** [comment] 2015-03-01 18:14
@daurnimator I adapted your workaround for luaposix too, thanks!

**Comment by gvvaughan** [comment] 2015-10-14 21:22
This seems to be fixed AFAICT.  Please reopen this, or a fresh issue if you prefer, should  you encounter it again in future.

**Closed** 2015-10-14 21:22 UTC
Labels: bug
