### ISSUE TITLE
Errors when compiling LuaPosix for Lua5.1 with FreeBSD 10.1

### ISSUE THREAD

**Issue by jeangit** [luaposix/luaposix#203] opened 2015-01-31 17:05 UTC
Hello, i'd like to compile LuaPosix for Lua5.1 with FreeBSD 10.1 (the port is working, but it's only for Lua5.2).

I've tried with luarocks , and directly from the sources, but i get some warnings:

```

make  all-am
  CC       ext/posix/posix.lo
In file included from ext/posix/posix.c:15:
./ext/posix/curses.c:1152:2: warning: implicitly declaring library function 'strlcpy' with type 'unsigned long
      (char *, const char *, unsigned long)'
        strlcpy (ti_capname, luaL_checkstring (L, 1), sizeof (ti_capname));
        ^
./ext/posix/curses.c:1152:2: note: please include the header <string.h> or explicitly provide a declaration for
      'strlcpy'

```

Well, not a problem i guess with the include of <string.h> (as suggested). I put here, because i was sure to have read here that this issue was solved.

```

In file included from ext/posix/posix.c:27:
./ext/posix/signal.c:145:54: warning: format specifies type 'int' but the argument has type 'sig_atomic_t'
      (aka 'long') [-Wformat]
                        fprintf(stderr,"error in signal handler %d: %s\n",signalno,lua_tostring(L,-1));
                                                                ~~        ^~~~~~~~
                                                                %ld

```

I don't know for this one, but i guess it's not a problem. I put here for reference.

But, here's come the serious stuff:

```

In file included from ext/posix/posix.c:31:
./ext/posix/sys/resource.c:156:16: error: use of undeclared identifier 'RLIM_SAVED_CUR'
        LPOSIX_CONST( RLIM_SAVED_CUR    );
                      ^
./ext/include/_helpers.c:110:25: note: expanded from macro 'LPOSIX_CONST'
                                        lua_pushinteger(L, _f);         \
                                                           ^
In file included from ext/posix/posix.c:31:
./ext/posix/sys/resource.c:157:16: error: use of undeclared identifier 'RLIM_SAVED_MAX'
        LPOSIX_CONST( RLIM_SAVED_MAX    );
                      ^
./ext/include/_helpers.c:110:25: note: expanded from macro 'LPOSIX_CONST'
                                        lua_pushinteger(L, _f);         \
                                                           ^

```

In file /usr/include/sys/resource.h , there is /* XXX Missing: RLIM_SAVED_MAX, RLIM_SAVED_CUR */

I've looked in the port for 5.2, but did'nt see any patch for RLIM_SAVED_xxx macro.
I don't know how they manage to compile it.

```

In file included from ext/posix/posix.c:32:
In file included from ./ext/posix/sys/socket.c:39:
/usr/include/netinet/udp.h:42:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short uh_sport;               /* source port */
        ^
/usr/include/netinet/udp.h:43:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short uh_dport;               /* destination port */
        ^
/usr/include/netinet/udp.h:44:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short uh_ulen;                /* udp length */
        ^
/usr/include/netinet/udp.h:45:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short uh_sum;                 /* udp checksum */
        ^
In file included from ext/posix/posix.c:32:

```

u_hort is heavily used in /usr/include of FreeBSD.
sys/types.h is probably missing in udp.h

```

./ext/posix/sys/socket.c:283:20: error: use of undeclared identifier 'PF_UNSPEC'
        hints.ai_family = PF_UNSPEC;
                          ^
./ext/posix/sys/socket.c:310:52: error: use of undeclared identifier 'PF_UNSPEC'
                        hints.ai_family   = optintfield(L, 3, "family", PF_UNSPEC);
                                                                        ^

```

PF_UNSPEC is defined in sys/socket.h
Another include is missing, i guess.

If i can do something more to help, don't hesitate !

Thank you.

**Comment by gvvaughan** [comment] 2015-01-31 17:42
Hi,

Thanks for the reports!

Taking your points in order:

1. Not sure what's up with the strlcpy warning, `ext/posix/curses.c` #includes `ext/include/_helpers.c` before `ext/include/strlcpy.c`, and both `ext/include/_helpers.c` and `ext/include/strlcpy.c` include the system `string.h`.  So even if configure detects a system strlcpy(), defines `HAVE_STRLCPY` and thus elides the contents of `ext/include/strlcpy.c`, the compiler should be seeing the contents of string.h before any reference to the `strlcpy` function.
1. I cast `signalno` to a long and use a `%ld` specifier now, which should work regardless of the bit-width of `sig_atomic_t`.
1. I patched `sys.resource` to only declare `RLIM_SAVED_CUR` and `RLIM_SAVED_MAX` if they are defined by the underlying runtime.
1. I moved the `sys/types.h` inclusion to before `netinet/udp.h`, so if you are correct about the missing include in FreeBSD 10.1's headers, this should fix it.
1. I don't have access to a FreeBSD machine, so you'll have to tell me what header is required to get a definition of `PF_UNSPEC` so I can add it to `sys.socket` (or what the equivalent macro is, so that I can define it myself in the source).

Note, that if you are having trouble compiling some part of luaposix that you don't actually use, you can simply remove the corresponding `#include` from `ext/posix/posix.c` to remove the troublesome module from your build.

HTH,
Gary

**Comment by jeangit** [comment] 2015-01-31 19:15
At first, thank you for replying so fast !

I've pulled your modifications, and it gets better.

Anyway, i still have some issues. May be they have all the same root:

So, strlncpy is still not defined : it seems that its definition is skipped, even with forcing inclusion of string.h.

Same problem with u_short definition.
Even with including sys/types.h just before the offending include at line 42, i always get the error.

Reading this : http://stackoverflow.com/questions/15393905/c-pcap-library-unknown-types-error , i tried and define directly u_short, just before the include:

(in /ext/posix/sys/socket.c )
42 typedef unsigned short u_short;
43 #include <netinet/udp.h>

and it works (of course, it's just an ugly workaround, but i cannot do better for now).

I bet it's the same problem with PF_UNSPEC

PF_UNSPEC is defined in :
sys/socket.h:#define    PF_UNSPEC       AF_UNSPEC

Hum… what is AF_UNSPEC ?
sys/socket.h:#define    AF_UNSPEC       0               /* unspecified */

Ok. Trying and include sys/socket did not change anything.

So i did the same as above:
i've just forced the typedef in ext/posix/sys/socket.c , like before:

#define PF_UNSPEC 0
(in /etc/posix/sys/socket.c)

And it compiles and links also.

Alas, when trying in Lua, i see there is a reference to Lua5.2:
lua_tointegerx

But that's another story, not related to this ticket.
(I had this problem when building the port with the Makefile provided in the port tree of FreeBSD. I thought it was related to the fact that the port was targeted for 5.2.)
And may be it disappears when building with LuaRocks, for Lua5.1 , and not directly with ./configure / make.

Anyway…
Thank you again for the quick answer :)

**Comment by gvvaughan** [comment] 2015-02-01 12:23
HI again,

1. strlcpy - what does configure say about it?  My machine sets `#define HAVE_STRLCPY 1` and at configure time, it says:

    ```
    checking for strlcpy... yes
   ```

   You might try commenting out the `HAVE_STRLCPY` definition in config.h and see if that makes any difference?  It's also possible that you need to put your compiler in the right mode to get a definition of strlcpy from the system runtime.  luaposix sets `LPOSIX_2001_COMPLIANT` or `LPOSIX_2008_COMPLIANT` based on whether the compiler headers set `_POSIX_C_SOURCE`, `_POSIX_VERSION` or `_XOPEN_SOURCE` appropriately, and then turns on and off it's support for certain features that require more POSIX compliance than the compiler mode.  You might have to pass additional `CFLAGS` at configure time to get everything you expect, such as `-std=c99` or similar.  Have a look at the recent patches for QNX support to see the sorts of things that were necessary to get that architecture to build in the right mode.

1. `u_short`, are you sure this is defined by `sys/types.h`?  Sometimes these things are in `stdint.h` or `sys/inttypes.h` or some other non-standard location.  Also, again, the compiler mode flags (and hence `_POSIX_C_SOURCE` etc.) might disable that part of the headers on your machine.

1. `AF_UNSPEC`, is for an **unspec**ified **a**ddress **f**amily and is used when filling structures for some of the BSD socket APIs; `PF_UNSPEC` is for an **unspec**ified **p**rotocol **f**amily, and is used in the same way, but for different APIs.  Again, I suspect your complier mode flags are selecting no BSD sockets, and defining away the contents of `sys/socket.h`.

1. `lua_tointegerx`, I seem to remember fixing that a while ago, and certainly grepping through the sources in master shows no matches in the current sources.  Are you picking up the correct Lua headers for the version of Lua you're building against?

HTH,
Gary

**Comment by gvvaughan** [comment] 2015-02-27 21:02
No response in a month, any reason to keep this issue open?

**Comment by gvvaughan** [comment] 2015-07-04 16:13
Assuming the original reporter was able to fix the problem, or moved on to something else.

**Comment by etosan** [comment] 2015-08-23 07:19
problem still persists on FreeBSD 10.2:

```text
gmake  all-am
gmake[1]: Entering directory '/usr/home/eto/luajit/luaposix'
  CC       ext/posix/posix.lo
In file included from ext/posix/posix.c:14:
./ext/posix/curses.c:1209:2: warning: implicitly declaring library function 'strlcpy' with type 'unsigned long
      (char *, const char *, unsigned long)'
        strlcpy (ti_capname, luaL_checkstring (L, 1), sizeof (ti_capname));
        ^
./ext/posix/curses.c:1209:2: note: please include the header <string.h> or explicitly provide a declaration for 'strlcpy'
In file included from ext/posix/posix.c:31:
In file included from ./ext/posix/sys/socket.c:40:
/usr/include/netinet/udp.h:42:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short uh_sport;               /* source port */
        ^
/usr/include/netinet/udp.h:43:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short uh_dport;               /* destination port */
        ^
/usr/include/netinet/udp.h:44:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short uh_ulen;                /* udp length */
        ^
/usr/include/netinet/udp.h:45:2: error: unknown type name 'u_short'; did you mean 'short'?
        u_short uh_sum;                 /* udp checksum */
        ^
In file included from ext/posix/posix.c:31:
./ext/posix/sys/socket.c:291:20: error: use of undeclared identifier 'PF_UNSPEC'
        hints.ai_family = PF_UNSPEC;
                          ^
./ext/posix/sys/socket.c:318:52: error: use of undeclared identifier 'PF_UNSPEC'
                        hints.ai_family   = optintfield(L, 3, "family", PF_UNSPEC);
                                                                        ^
1 warning and 6 errors generated.
Makefile:1456: recipe for target 'ext/posix/posix.lo' failed
gmake[1]: *** [ext/posix/posix.lo] Error 1
gmake[1]: Leaving directory '/usr/home/eto/luajit/luaposix'
Makefile:1012: recipe for target 'all' failed
gmake: *** [all] Error 2
```
I am not very knowleadgeable about deep compiler stuff. Moving include directive with sys/types.h up and down doesn't help. However jeangit's hack do "solve" issue.

According to my research attempt,
u_short is defined here:
```text
ag u_short /usr/include/sys/types.h  
51:typedef	unsigned short	u_short;
```
and only reference to PF_UNSPEC i see here:

```
ag PF_UNSPEC /usr/include            
/usr/include/sys/socket.h
319:#define	PF_UNSPEC	AF_UNSPEC
```

**Comment by gvvaughan** [comment] 2015-08-23 10:45
Hi Martin,

Thanks for the feedback, and the error message output.  If you don't mind, let's try to fix one issue at a time... starting with the easiest one: undefined strlcpy...

Does the following patch get rid of that warning?

```
diff --git a/ext/include/strlcpy.c b/ext/include/strlcpy.c
index 361eefd..792cb9c 100644
--- a/ext/include/strlcpy.c
+++ b/ext/include/strlcpy.c
@@ -32,6 +32,8 @@
 
 #include <config.h>
 
+#include <string.h>	/* To get the system strlcpy prototype. */
+
 #ifndef HAVE_STRLCPY
 
 #if defined LIBC_SCCS && ! defined lint
@@ -39,7 +41,6 @@ static char *rcsid = "$OpenBSD: strlcpy.c,v 1.4 1999/05/01 18:56:41 millert Exp
 #endif /* LIBC_SCCS and not lint */
 
 #include <sys/types.h>
-#include <string.h>
 
 static size_t strlcpy(char *dst, const char *src, size_t siz);
 
```

**Comment by gvvaughan** [comment] 2015-08-23 12:06
Actually, I take back that previous patch.  I think the real problem is to do with definition of supported feature macros in the system headers (see `/usr/include/sys/cdefs.h`), where it looks like my declaration of `XOPEN_SOURCE=700` turns off `_BSD_VISIBLE` and `_XSI_VISIBLE` macros that enable the features luaposix relies on... so maybe the following is all that's needed?

```
--- configure.old       2015-08-23 12:59:01.000000000 +0100
+++ configure   2015-08-23 12:59:26.000000000 +0100
@@ -4920,7 +4920,7 @@
 
     ;;
 
-  darwin*|openbsd*)
+  darwin*|freebsd*|openbsd*)
     # Setting _XOPEN_SOURCE here messes up header declarations, but
     # all functions luaposix can bind are available without it.
     POSIX_EXTRA_CPPFLAGS=-DLPOSIX_2008_COMPLIANT
diff --git a/configure.ac b/configure.ac
index 89a2feb..1a1f04c 100644
--- a/configure.ac
+++ b/configure.ac
@@ -38,7 +38,7 @@ case $host_os in
     AC_SUBST([POSIX_EXTRA_CPPFLAGS], [-DLPOSIX_2001_COMPLIANT])
     ;;
 
-  darwin*|openbsd*)
+  darwin*|freebsd*|openbsd*)
     # Setting _XOPEN_SOURCE here messes up header declarations, but
     # all functions luaposix can bind are available without it.
     AC_SUBST([POSIX_EXTRA_CPPFLAGS], [-DLPOSIX_2008_COMPLIANT])
```

So, if you could apply this patch instead of the previous one, rerun `./configure` and `make` and let me know whether it gets any further, I'll apply the patch here and make a new release -- or work on fixing any remaining errors you are encounter :)

Cheers,
Gary

**Comment by etosan** [comment] 2015-08-23 21:33
Okay, I deleted everything beside .git.
Then I fetched patch snippet and saved it into ../luaposix.configure.patch
Next I did :

```sh
git checkout .
./bootstrap
mv configure configure.old
patch configure.old -i ../luaposix.configure.patch -o configure
```
result of patch operation:
```text
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- configure.old       2015-08-23 12:59:01.000000000 +0100
|+++ configure   2015-08-23 12:59:26.000000000 +0100
--------------------------
Patching file configure.old using Plan A...
Hunk #1 succeeded at 4920.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/configure.ac b/configure.ac
|index 89a2feb..1a1f04c 100644
|--- a/configure.ac
|+++ b/configure.ac
--------------------------
Patching file configure.ac using Plan A...
Hunk #1 succeeded at 38 with fuzz 1.
done
```
then ran ./configure, gmake.

 resulting binary seems to be put into:

```text
% ls ext/posix/.libs/posix.so                  
-rwxr-xr-x 1 eto eto 387K 2015-08-23 23:10 ext/posix/.libs/posix.so

%ext/posix/.libs/posix.so:
	libcrypt.so.5 => /lib/libcrypt.so.5 (0x80162c000)
	librt.so.1 => /usr/lib/librt.so.1 (0x80184c000)
	libncursesw.so.8 => /lib/libncursesw.so.8 (0x801a52000)
	libc.so.7 => /lib/libc.so.7 (0x800821000)
	libthr.so.3 => /lib/libthr.so.3 (0x801ca7000)
```

Installed the lib:
```sh
sudo gmake install
```
So now posix.so should be availible to lua51 and luajit

Verification:
```text
 % pkg info 'lua*'
lua51-5.1.5_9
lua51-luafilesystem-1.6.3
lua51-luasocket-3.0r1
lua51-pty-1.25
luajit-2.0.4
```
All looks good, so I do

```text
%cd examples
% lua51 dir.lua 
lua51: error loading module 'posix.dirent' from file '/usr/local/lib/lua/5.1/posix.so':
	/usr/local/lib/lua/5.1/posix.so: Undefined symbol "fdatasync"
stack traceback:
	[C]: ?
	[C]: in function 'require'
	dir.lua:1: in main chunk
	[C]: ?
% luajit ping.lua 
luajit: error loading module 'posix' from file '/usr/local/lib/lua/5.1/posix.so':
	/usr/local/lib/lua/5.1/posix.so: Undefined symbol "fdatasync"
stack traceback:
	[C]: at 0x00461c60
	[C]: in function 'require'
	ping.lua:1: in main chunk
	[C]: at 0x00404000
```

So I got further, but seems like "fdatasync" symbol is missing. According to internet fdatasync should be in  **unistd.h**. But FreeBSD doesn't seem to have it?

```text
%cd/usr/include 
% ag fdatasync
bsm/audit_kevents.h
699:#define	AUE_FDATASYNC		AUE_NULL
% ag sync unistd.h
192:#define	_SC_ASYNCHRONOUS_IO	28
202:#define	_SC_FSYNC		38
204:#define	_SC_SYNCHRONIZED_IO	40
386:int	 fsync(int);
465:void	 sync(void);
489:int	 async_daemon(void);
```

**Comment by etosan** [comment] 2015-08-23 21:48
Btw I don't have gcc installed so I guess it's being compiled by clang.

There seems to be some stub in *gnulib/lib/fdatasync.c* but I don't understand project complex as this. Why it doesn't get applied?

**Comment by gvvaughan** [comment] 2015-08-23 22:03
Hi Martin,

Thanks for testing the patch so quickly.  I've just pushed it to master, along with another to follow presently which disables fdatasync on machines that don't have it -- even if they do claim POSIX.2001 compliance ;-)

Gnulib is only included for autoconf enhancements... I don't use any of the C code from Gnulib.  Unfortunately the bulk of C sources inside it are GPLed, so linking with them would prevent distributing luaposix as MIT licensed.  Also, the gnulib modules are a rats nest of interdependencies, so pulling in just one or two things could end up adding dozens of modules and multiply the size of the compiled posix.so library.  On your own machine, there is nothing preventing you from building the gnulib fdatasync module if the licensing issue is not a problem to you.

Please let me know if everything works for you now, and I'll make a new release with the fixes in.

Cheers,
Gary

**Comment by etosan** [comment] 2015-08-23 22:18
Great now it compiles fine but there is new error:

```
% lua51 glob.lua 
lua51: error loading module 'posix' from file '/usr/local/lib/lua/5.1/posix.so':
	Undefined symbol "luaopen_posix"
stack traceback:
	[C]: ?
	[C]: in function 'require'
	glob.lua:1: in main chunk
 	[C]: ?

% luajit glob.lua 
luajit: error loading module 'posix' from file '/usr/local/lib/lua/5.1/posix.so':
	Undefined symbol "luaopen_posix"
stack traceback:
	[C]: at 0x00461c60
	[C]: in function 'require'
	glob.lua:1: in main chunk
	[C]: at 0x00404000
```

on my linux box when i do:

```
strings /usr/lib/lua/5.1/posix_c.so | grep luaopen_posix
luaopen_posix_c
```

On FreeBSD:

```
% strings /usr/local/lib/lua/5.1/posix.so | grep luaopen_posix 
luaopen_posix_ctype
luaopen_posix_curses
luaopen_posix_curses_chstr
luaopen_posix_curses_window
luaopen_posix_dirent
luaopen_posix_errno
luaopen_posix_fcntl
luaopen_posix_fnmatch
luaopen_posix_getopt
luaopen_posix_glob
luaopen_posix_grp
luaopen_posix_libgen
luaopen_posix_poll
luaopen_posix_pwd
luaopen_posix_sched
luaopen_posix_signal
luaopen_posix_stdio
luaopen_posix_stdlib
luaopen_posix_sys_msg
luaopen_posix_sys_resource
luaopen_posix_sys_socket
luaopen_posix_sys_stat
luaopen_posix_sys_statvfs
luaopen_posix_sys_time
luaopen_posix_sys_times
luaopen_posix_sys_utsname
luaopen_posix_sys_wait
luaopen_posix_syslog
luaopen_posix_termio
luaopen_posix_time
luaopen_posix_unistd
luaopen_posix_utime
```
I guess it's caused by my linux version being older? No idea.

**Comment by gvvaughan** [comment] 2015-08-23 22:31
Hi Martin,

Yes the Linux symbols are from an ancient luaposix where the kernel was in posix_c.so and smushed all of the symbols into one namespace.

It looks like you haven't set your LUA_PATH to find the install `posix.lua` and helpers that `make install` should have installed for you (or they didn't install correctly), and which you will need for compatibility with the old smushed apis.

HTH!

**Comment by gvvaughan** [comment] 2015-08-23 22:38
P.S. If you don't mind installing `lyaml` and `specl`, you can run `make check V=1` in the built tree before you install to verify that the build is working correctly.

**Comment by etosan** [comment] 2015-08-23 23:07
I see, so various lua stubs in directory, are needed. 

I wanted to get to "native" lua install so I made specl and lyaml to be /usr/bin/true with envvars as suggested by bootstrap. 

Copying stubs makes curses example work, but rest is failing with bit32.lua missing. I though this is lua LuaBitOp, but that doesn't seem to be the case?

Anyway specl and lyaml seem to depend ldoc and that depends on penlight and none of this is packaged on FreeBSD and I have no clue how rocks work.

I am going to sleep tonight. I hope that I will get some time soon to look at this more.

Thanks for the great help, so far this is unsolved.

**Comment by gvvaughan** [comment] 2015-08-24 00:56
The bit32 issue is #206.

You can resolve it by installing the bit32 module from https://github.com/keplerproject/lua-compat-5.2/blob/master/lbitlib.c, or fetching and reverse applying the luaposix patch that removed the native bit32 implementation: https://github.com/luaposix/luaposix/commit/a7bdfab414b9d633b18bf6368c8e66dcb684b70c but not luabitop in this case.

None of this is necessary with  Lua >= 5.2 (with LUA_COMPAT_5_2 defined at compile-time) of course, and is much easier with luarocks, which will pull in the bit32 dependency for luajit or lua-5.1, or use the existing APIs:

```bash
luarocks install luaposix
```

@rrthomas I'm still not entirely happy with https://github.com/luaposix/luaposix/commit/a7bdfab414b9d633b18bf6368c8e66dcb684b70c because of the ongoing difficulties for non-rocks users, and ensuing support required. Maybe not worth the 100LOC we saved IMHO?

**Comment by rrthomas** [comment] 2015-08-24 10:22
Non-rocks users ← should be unsupported. We could make this clearer in the README.

**Comment by gvvaughan** [comment] 2015-08-25 13:35
@rrthomas ack, and likewise for our other Lua project README files...  added to my TODO list.

@jeangit, @etosan I'm closing this issue again, as FreeBSD seems to be working properly  now (u_short, strlcpy, signalno specifier, and PF_UNSPEC, RLIM_SAVED_CUR & RLIM_SAVED_MAX definitions all solved). Thank you both for reporting the problems and helping me port luaposix to a new platform... much appreciated!

@etosan I should have mentioned before you only need LDoc and Penlight for bootstrapping of Specl and lyaml, they are not runtime dependencies. If you install from release tarballs, the documentation is already generated.

A toute le monde: I am planning to remove dependencies on bootstrap. autotools, gnulib, and slingshot entirely at some point, after which non-luarocks builds will involve building in-tree and manually copying the right files into directories on an appropriate LUA_PATH/LUA_CPATH.

**Closed by gvvaughan** 2015-08-25 13:35 UTC
Labels: enhancement

**Comment by etosan** [comment] 2015-09-30 19:58
I haven't found time to check this out, as I got luajit and ljsyscal somewhat working for set of scripts I was working on. However thank you for looking into it! I hope you'll provide lua5.1 backwards compat. as long as possible.
