### ISSUE TITLE
luaposix fails to install on my Ubuntu 16.04 with lua 5.1

### ISSUE THREAD

**Issue by sebpiq** [luaposix/luaposix#277] opened 2017-05-08 03:26 UTC
```
$ sudo luarocks --verbose install luaposix

os.execute: 	'wget' --no-check-certificate --no-cache --user-agent='LuaRocks/2.2.0 linux-x86_64 via wget' --quiet --timeout=30 --tries=1  --timestamping  'https://rocks.moonscript.org/manifest-5.1.zip'
Results: 1
  1 (number): 0

os.execute: 	unzip -n '/home/spiq/.cache/luarocks/https___rocks.moonscript.org/manifest-5.1.zip'
Archive:  /home/spiq/.cache/luarocks/https___rocks.moonscript.org/manifest-5.1.zip
  inflating: manifest-5.1            
Results: 1
  1 (number): 0
Installing https://rocks.moonscript.org/luaposix-34.0-1.src.rock...
Using https://rocks.moonscript.org/luaposix-34.0-1.src.rock... switching to 'build' mode

os.execute: 	'wget' --no-check-certificate --no-cache --user-agent='LuaRocks/2.2.0 linux-x86_64 via wget' --quiet --timeout=30 --tries=1  --output-document  '/tmp/luarocks_luarocks-rock-luaposix-34.0-1-2823/luaposix-34.0-1.src.rock' 'https://rocks.moonscript.org/luaposix-34.0-1.src.rock'
Results: 1
  1 (number): 0

os.execute: 	unzip -n '/tmp/luarocks_luarocks-rock-luaposix-34.0-1-2823/luaposix-34.0-1.src.rock'
Archive:  /tmp/luarocks_luarocks-rock-luaposix-34.0-1-2823/luaposix-34.0-1.src.rock
  inflating: luaposix-34.0-1.rockspec  
 extracting: v34.0.zip               
Results: 1
  1 (number): 0

os.execute: 	unzip -n 'v34.0.zip'
Archive:  v34.0.zip
769e91a13e409aa4c3bae55bcb16b2f951864243
   creating: luaposix-34.0/
  inflating: luaposix-34.0/.gitignore  
 extracting: luaposix-34.0/.slackid  
  inflating: luaposix-34.0/.travis.yml  
  inflating: luaposix-34.0/AUTHORS   
  inflating: luaposix-34.0/ChangeLog.old  
  inflating: luaposix-34.0/LICENSE   
  inflating: luaposix-34.0/NEWS.md   
  inflating: luaposix-34.0/README.md  
   creating: luaposix-34.0/build-aux/
  inflating: luaposix-34.0/build-aux/config.ld.in  
  inflating: luaposix-34.0/build-aux/luke  
   creating: luaposix-34.0/doc/
   creating: luaposix-34.0/doc/examples/
  inflating: luaposix-34.0/doc/examples/abstract-ns-client.lua  
  inflating: luaposix-34.0/doc/examples/abstract-ns-client.lua.html  
  inflating: luaposix-34.0/doc/examples/abstract-ns-server.lua  
  inflating: luaposix-34.0/doc/examples/abstract-ns-server.lua.html  
  inflating: luaposix-34.0/doc/examples/dir.lua  
  inflating: luaposix-34.0/doc/examples/dir.lua.html  
  inflating: luaposix-34.0/doc/examples/dup2.lua  
  inflating: luaposix-34.0/doc/examples/dup2.lua.html  
  inflating: luaposix-34.0/doc/examples/fork.lua  
  inflating: luaposix-34.0/doc/examples/fork.lua.html  
  inflating: luaposix-34.0/doc/examples/fork2.lua  
  inflating: luaposix-34.0/doc/examples/fork2.lua.html  
  inflating: luaposix-34.0/doc/examples/getopt.lua  
  inflating: luaposix-34.0/doc/examples/getopt.lua.html  
  inflating: luaposix-34.0/doc/examples/glob.lua  
  inflating: luaposix-34.0/doc/examples/glob.lua.html  
  inflating: luaposix-34.0/doc/examples/limit.lua  
  inflating: luaposix-34.0/doc/examples/limit.lua.html  
  inflating: luaposix-34.0/doc/examples/lock.lua  
  inflating: luaposix-34.0/doc/examples/lock.lua.html  
  inflating: luaposix-34.0/doc/examples/netlink-uevent.lua  
  inflating: luaposix-34.0/doc/examples/netlink-uevent.lua.html  
  inflating: luaposix-34.0/doc/examples/ping.lua  
  inflating: luaposix-34.0/doc/examples/ping.lua.html  
  inflating: luaposix-34.0/doc/examples/poll.lua  
  inflating: luaposix-34.0/doc/examples/poll.lua.html  
  inflating: luaposix-34.0/doc/examples/rt_sched.lua  
  inflating: luaposix-34.0/doc/examples/rt_sched.lua.html  
  inflating: luaposix-34.0/doc/examples/signal.lua  
  inflating: luaposix-34.0/doc/examples/signal.lua.html  
  inflating: luaposix-34.0/doc/examples/socket.lua  
  inflating: luaposix-34.0/doc/examples/socket.lua.html  
  inflating: luaposix-34.0/doc/examples/termios.lua  
  inflating: luaposix-34.0/doc/examples/termios.lua.html  
  inflating: luaposix-34.0/doc/examples/tree.lua  
  inflating: luaposix-34.0/doc/examples/tree.lua.html  
  inflating: luaposix-34.0/doc/index.html  
  inflating: luaposix-34.0/doc/ldoc.css  
   creating: luaposix-34.0/doc/modules/
  inflating: luaposix-34.0/doc/modules/posix.ctype.html  
  inflating: luaposix-34.0/doc/modules/posix.dirent.html  
  inflating: luaposix-34.0/doc/modules/posix.errno.html  
  inflating: luaposix-34.0/doc/modules/posix.fcntl.html  
  inflating: luaposix-34.0/doc/modules/posix.fnmatch.html  
  inflating: luaposix-34.0/doc/modules/posix.glob.html  
  inflating: luaposix-34.0/doc/modules/posix.grp.html  
  inflating: luaposix-34.0/doc/modules/posix.html  
  inflating: luaposix-34.0/doc/modules/posix.libgen.html  
  inflating: luaposix-34.0/doc/modules/posix.poll.html  
  inflating: luaposix-34.0/doc/modules/posix.pwd.html  
  inflating: luaposix-34.0/doc/modules/posix.sched.html  
  inflating: luaposix-34.0/doc/modules/posix.signal.html  
  inflating: luaposix-34.0/doc/modules/posix.stdio.html  
  inflating: luaposix-34.0/doc/modules/posix.stdlib.html  
  inflating: luaposix-34.0/doc/modules/posix.sys.msg.html  
  inflating: luaposix-34.0/doc/modules/posix.sys.resource.html  
  inflating: luaposix-34.0/doc/modules/posix.sys.socket.html  
  inflating: luaposix-34.0/doc/modules/posix.sys.stat.html  
  inflating: luaposix-34.0/doc/modules/posix.sys.statvfs.html  
  inflating: luaposix-34.0/doc/modules/posix.sys.time.html  
  inflating: luaposix-34.0/doc/modules/posix.sys.times.html  
  inflating: luaposix-34.0/doc/modules/posix.sys.utsname.html  
  inflating: luaposix-34.0/doc/modules/posix.sys.wait.html  
  inflating: luaposix-34.0/doc/modules/posix.syslog.html  
  inflating: luaposix-34.0/doc/modules/posix.termio.html  
  inflating: luaposix-34.0/doc/modules/posix.time.html  
  inflating: luaposix-34.0/doc/modules/posix.unistd.html  
  inflating: luaposix-34.0/doc/modules/posix.utime.html  
   creating: luaposix-34.0/ext/
   creating: luaposix-34.0/ext/include/
  inflating: luaposix-34.0/ext/include/_helpers.c  
  inflating: luaposix-34.0/ext/include/compat-5.2.c  
  inflating: luaposix-34.0/ext/include/compat-5.2.h  
   creating: luaposix-34.0/ext/posix/
  inflating: luaposix-34.0/ext/posix/ctype.c  
  inflating: luaposix-34.0/ext/posix/dirent.c  
  inflating: luaposix-34.0/ext/posix/errno.c  
  inflating: luaposix-34.0/ext/posix/fcntl.c  
  inflating: luaposix-34.0/ext/posix/fnmatch.c  
  inflating: luaposix-34.0/ext/posix/glob.c  
  inflating: luaposix-34.0/ext/posix/grp.c  
  inflating: luaposix-34.0/ext/posix/libgen.c  
  inflating: luaposix-34.0/ext/posix/poll.c  
  inflating: luaposix-34.0/ext/posix/posix.c  
  inflating: luaposix-34.0/ext/posix/pwd.c  
  inflating: luaposix-34.0/ext/posix/sched.c  
  inflating: luaposix-34.0/ext/posix/signal.c  
  inflating: luaposix-34.0/ext/posix/stdio.c  
  inflating: luaposix-34.0/ext/posix/stdlib.c  
   creating: luaposix-34.0/ext/posix/sys/
  inflating: luaposix-34.0/ext/posix/sys/msg.c  
  inflating: luaposix-34.0/ext/posix/sys/resource.c  
  inflating: luaposix-34.0/ext/posix/sys/socket.c  
  inflating: luaposix-34.0/ext/posix/sys/stat.c  
  inflating: luaposix-34.0/ext/posix/sys/statvfs.c  
  inflating: luaposix-34.0/ext/posix/sys/time.c  
  inflating: luaposix-34.0/ext/posix/sys/times.c  
  inflating: luaposix-34.0/ext/posix/sys/utsname.c  
  inflating: luaposix-34.0/ext/posix/sys/wait.c  
  inflating: luaposix-34.0/ext/posix/syslog.c  
  inflating: luaposix-34.0/ext/posix/termio.c  
  inflating: luaposix-34.0/ext/posix/time.c  
  inflating: luaposix-34.0/ext/posix/unistd.c  
  inflating: luaposix-34.0/ext/posix/utime.c  
   creating: luaposix-34.0/lib/
   creating: luaposix-34.0/lib/posix/
  inflating: luaposix-34.0/lib/posix/_argcheck.lua  
  inflating: luaposix-34.0/lib/posix/compat.lua  
  inflating: luaposix-34.0/lib/posix/deprecated.lua  
  inflating: luaposix-34.0/lib/posix/init.lua  
  inflating: luaposix-34.0/lib/posix/sys.lua  
  inflating: luaposix-34.0/lib/posix/util.lua  
  inflating: luaposix-34.0/lib/posix/version.lua.in  
  inflating: luaposix-34.0/luaposix-34.0-1.rockspec  
  inflating: luaposix-34.0/lukefile  
   creating: luaposix-34.0/specs/
  inflating: luaposix-34.0/specs/lposix_spec.yaml  
  inflating: luaposix-34.0/specs/posix_compat_spec.yaml  
  inflating: luaposix-34.0/specs/posix_ctype_spec.yaml  
  inflating: luaposix-34.0/specs/posix_deprecated_spec.yaml  
  inflating: luaposix-34.0/specs/posix_dirent_spec.yaml  
  inflating: luaposix-34.0/specs/posix_fcntl_spec.yaml  
  inflating: luaposix-34.0/specs/posix_fnmatch_spec.yaml  
  inflating: luaposix-34.0/specs/posix_glob_spec.yaml  
  inflating: luaposix-34.0/specs/posix_grp_spec.yaml  
  inflating: luaposix-34.0/specs/posix_pwd_spec.yaml  
  inflating: luaposix-34.0/specs/posix_signal_spec.yaml  
  inflating: luaposix-34.0/specs/posix_spec.yaml  
  inflating: luaposix-34.0/specs/posix_stdio_spec.yaml  
  inflating: luaposix-34.0/specs/posix_stdlib_spec.yaml  
  inflating: luaposix-34.0/specs/posix_sys_msg_spec.yaml  
  inflating: luaposix-34.0/specs/posix_sys_resource_spec.yaml  
  inflating: luaposix-34.0/specs/posix_sys_socket_spec.yaml  
  inflating: luaposix-34.0/specs/posix_sys_stat_spec.yaml  
  inflating: luaposix-34.0/specs/posix_sys_statvfs_spec.yaml  
  inflating: luaposix-34.0/specs/posix_sys_time_spec.yaml  
  inflating: luaposix-34.0/specs/posix_sys_times_spec.yaml  
  inflating: luaposix-34.0/specs/posix_sys_utsname_spec.yaml  
  inflating: luaposix-34.0/specs/posix_syslog_spec.yaml  
  inflating: luaposix-34.0/specs/posix_time_spec.yaml  
  inflating: luaposix-34.0/specs/posix_unistd_spec.yaml  
  inflating: luaposix-34.0/specs/posix_version_spec.yaml  
  inflating: luaposix-34.0/specs/spec_helper.lua  
Results: 1
  1 (number): 0
build-aux/luke package="luaposix" version="34.0-1" PREFIX="/usr/local/lib/luarocks/rocks/luaposix/34.0-1" LUA="/usr/bin/lua5.1" LUA_INCDIR="/usr/include/lua5.1" CFLAGS="-O2 -fPIC" LIBFLAG="-shared" LIB_EXTENSION="so" OBJ_EXTENSION="o" INST_LIBDIR="/usr/local/lib/luarocks/rocks/luaposix/34.0-1/lib" INST_LUADIR="/usr/local/lib/luarocks/rocks/luaposix/34.0-1/lua"

os.execute: 	build-aux/luke package="luaposix" version="34.0-1" PREFIX="/usr/local/lib/luarocks/rocks/luaposix/34.0-1" LUA="/usr/bin/lua5.1" LUA_INCDIR="/usr/include/lua5.1" CFLAGS="-O2 -fPIC" LIBFLAG="-shared" LIB_EXTENSION="so" OBJ_EXTENSION="o" INST_LIBDIR="/usr/local/lib/luarocks/rocks/luaposix/34.0-1/lib" INST_LUADIR="/usr/local/lib/luarocks/rocks/luaposix/34.0-1/lua"
lua: build-aux/luke:120: attempt to concatenate local 'found' (a nil value)
stack traceback:
	build-aux/luke:120: in function 'check_executable_in_path'
	build-aux/luke:197: in function 'block'
	build-aux/luke:432: in function 'dropuntil'
	build-aux/luke:197: in function <build-aux/luke:197>
	(tail call): ?
	(tail call): ?
	build-aux/luke:432: in function 'dropuntil'
	build-aux/luke:210: in function <build-aux/luke:210>
	(tail call): ?
	(tail call): ?
	(tail call): ?
	build-aux/luke:220: in function 'config_ldoc'
	build-aux/luke:244: in function 'build_modules'
	build-aux/luke:254: in function 'main'
	build-aux/luke:618: in main chunk
	[C]: ?
Results: 1
  1 (number): 256

Error: Build error: Failed building.
```

**Comment by CMB** [comment] 2017-05-10 09:07
This is basically a duplicate of issue 276.

**Comment by gvvaughan** [comment] 2017-05-13 23:33
Yep, closing as a dup.

I have a fix ready to sync from luke, which i'll push when I'm back at my computer. In the mean time if you wrap the `found` symbol at line 120 with `tostring` that will work around the nil value you are hitting.

**Closed by gvvaughan** 2017-05-13 23:33 UTC

**Comment by sebpiq** [comment] 2017-05-14 07:50
ok thanks for the workaround! I will try to make this work...
