### ISSUE TITLE
luke: fatal: required symbol 'crypt' not found in any of libc, libcrypt

### ISSUE THREAD

**Issue by woodgear** [luaposix/luaposix#343] opened 2021-11-10 00:09 UTC
os: ubuntu 20.04 x86
lua: 5.1.0
luarocks: 3.8.0
reproduce
```bash
luarocks install luaposix        Installing https://luarocks.org/luaposix-35.1-1.src.rock

luaposix 35.1-1 depends on lua >= 5.1, < 5.5 (5.1-1 provided by VM)
luaposix 35.1-1 depends on bit32 (5.3.5.1-1 installed)
/home/cong/.luaver/lua/5.1/bin/lua build-aux/luke package="luaposix" version="35.1" PREFIX="/home/cong/.luaver/luarocks/3.8.0_5.1/lib/luarocks/rocks-5.1/luaposix/35.1-1" LUA="/home/cong/.luaver/lua/5.1/bin/lua" LUA_INCDIR="/home/cong/.luaver/lua/5.1/include" CFLAGS="-O2 -fPIC" LIBFLAG="-shared" LIB_EXTENSION="so" OBJ_EXTENSION="o" INST_LIBDIR="/home/cong/.luaver/luarocks/3.8.0_5.1/lib/luarocks/rocks-5.1/luaposix/35.1-1/lib" INST_LUADIR="/home/cong/.luaver/luarocks/3.8.0_5.1/lib/luarocks/rocks-5.1/luaposix/35.1-1/lua"
luke: fatal: required symbol 'crypt' not found in any of libc, libcrypt
```
it seems resolved by #8 .
i have already installed liblua5.1-dev,libcrypt-dev,but still.

**Comment by gvvaughan** [comment] 2021-11-10 00:48
If it’s resolved by #8 from 9 years ago, why are you still affected? If it’s because the last release is still using an ancient luke, I can upload a new release to fix it.

mid it’s something else, can you reply with the debug output of running luke, please?

**Comment by woodgear** [comment] 2021-11-10 02:51
```bash
./build-aux/luke --debug
   DEBUG: ldoc not found
   DEBUG: found /usr/bin/true
   DEBUG: found /usr/bin/cc
   DEBUG: cc -c -O2 -I.sys.socket_INCDIR  /tmp/lua_bnBDij.c
   DEBUG: cc -c -O2 -I.unistd_INCDIR  /tmp/lua_9yggvm.c
   DEBUG: cc -c -O2 -I.sys.socket_INCDIR  /tmp/lua_oI9zKn.c
   DEBUG: cc -c -O2 -I.sys.msg_INCDIR  /tmp/lua_MyNwHl.c
   DEBUG: cc -c -O2 -I.sys.socket_INCDIR  /tmp/lua_3PqtIn.c
   DEBUG: cc -c -O2 -I.sched_INCDIR  /tmp/lua_eXC8Jl.c
   DEBUG: cc -c -O2 -I.unistd_INCDIR  /tmp/lua_Izr6il.c
   DEBUG: cc -O2 -I.time_INCDIR  -o /tmp/lua_mBfoGm /tmp/lua_WEt8Nj.c -L.time_LIBDIR   
   DEBUG: /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
   DEBUG: (.text+0x24): undefined reference to `main'
   DEBUG: collect2: error: ld returned 1 exit status
   DEBUG: 
   DEBUG: cc -O2 -I.unistd_INCDIR  -o /tmp/lua_jIl32j /tmp/lua_YsibUm.c -L.unistd_LIBDIR    
   DEBUG: /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
   DEBUG: (.text+0x24): undefined reference to `main'
   DEBUG: collect2: error: ld returned 1 exit status
   DEBUG: 
   DEBUG: cc -O2 -I.unistd_INCDIR  -o /tmp/lua_IETMFm /tmp/lua_LNsMjl.c -L.unistd_LIBDIR  -lcrypt  
   DEBUG: /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
   DEBUG: (.text+0x24): undefined reference to `main'
   DEBUG: collect2: error: ld returned 1 exit status
   DEBUG: 
luke: fatal: required symbol 'crypt' not found in any of libc, libcrypt
```

**Comment by woodgear** [comment] 2021-11-11 01:48
update to latest master and all things fine.

**Comment by gvvaughan** [comment] 2021-11-11 01:49
Awesome I’ll make a new release by the weekend then.. thanks for letting me know :-)

**Comment by gvvaughan** [comment] 2021-11-12 01:58
Actually @woodgear, luaposix-35.1 already was that release from the tip of luaposix/luaposix master, and it includes build-aux/luke generated from master of gvvaughan/luke.

What was it that you updated to latest master of to fix all things?  Or was it a non-reproducible issue due to something in your environment?

**Closed** 2021-12-30 02:41 UTC
